<!-- Generated by Copilot -->
<!-- Ad-hoc preview page: renders a ComparisonDetail uploaded client-side.
     Redirects to / if no upload data is present (e.g. direct navigation). -->
<template>
  <div class="space-y-6">
    <!-- Back link -->
    <NuxtLink to="/" class="inline-flex items-center gap-1 text-sm text-blue-600 hover:text-blue-800">
      ← Back to Dashboard
    </NuxtLink>

    <!-- Preview banner -->
    <div class="flex items-start gap-3 bg-amber-50 border border-amber-300 rounded-xl px-5 py-4">
      <svg class="h-5 w-5 text-amber-500 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
      </svg>
      <div class="flex-1">
        <p class="text-sm font-semibold text-amber-800">Preview mode</p>
        <p class="text-xs text-amber-700 mt-0.5">
          This comparison was loaded from an uploaded file and is not saved to the system.
          Refreshing the page will clear it.
        </p>
      </div>
      <button
        class="text-amber-500 hover:text-amber-700 transition-colors p-1 rounded-lg hover:bg-amber-100"
        aria-label="Dismiss and go back"
        title="Dismiss and go back to dashboard"
        @click="onDismiss"
      >
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <!-- Fund header card -->
    <div class="bg-white rounded-xl border border-gray-200 p-6">
      <div class="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 class="text-xl font-bold text-gray-900">{{ detail.fund.name }}</h1>
          <p class="mt-1 text-sm text-gray-500">
            CIK: <span class="font-mono text-gray-700">{{ detail.fund.cik }}</span>
            &nbsp;·&nbsp;
            Generated: {{ fmtTs(detail.fund.generated_at) }}
          </p>
        </div>
        <StatusBadge :status="overallStatus" class="text-sm px-3 py-1" />
      </div>
    </div>

    <!-- Tabbed detail -->
    <div class="bg-white rounded-xl border border-gray-200 p-6">
      <BaseTabs :tabs="tabs" default-tab="matrix">
        <template #default="{ active }">
          <div v-show="active === 'matrix'">
            <ComparisonMatrix :d="detail" />
          </div>

          <div v-show="active === 'nav'">
            <TabNavTab :comparison="detail.comparison" :performance="detail.performance" />
          </div>

          <div v-show="active === 'distributions'">
            <TabDistributionsTab :distributions="detail.distributions" />
          </div>

          <div v-show="active === 'shares'">
            <TabSharesTab :shares="detail.shares_outstanding" />
          </div>

          <div v-show="active === 'gpp'">
            <TabGppTab :gpp="detail.gpp_data" />
          </div>
        </template>
      </BaseTabs>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ComparisonDetail } from '~/types/comparison'

const { uploadedComparison, clearUploadedComparison } = useUploadedComparison()

// Guard: redirect to dashboard if the user navigated here without uploading a file
if (!uploadedComparison.value) {
  await navigateTo('/')
}

// Non-null assertion safe here: if null we redirected above
const detail = uploadedComparison.value as ComparisonDetail

const tabs = [
  { key: 'matrix', label: '⚖️ Side-by-Side Comparison' },
  { key: 'nav', label: 'NAV Detail' },
  { key: 'distributions', label: 'Distributions' },
  { key: 'shares', label: 'Shares Outstanding' },
  { key: 'gpp', label: 'GPP Data' },
]

const overallStatus = computed(() => {
  const classes = Object.values(detail?.comparison?.per_class ?? {})
  if (classes.length === 0) return 'unknown'
  if (classes.some((c: { status: string }) => c.status === 'error')) return 'error'
  if (classes.some((c: { status: string }) => c.status === 'mismatch')) return 'mismatch'
  if (classes.every((c: { status: string }) => c.status === 'match')) return 'match'
  return 'ok'
})

function fmtTs(ts: string) {
  try {
    return new Date(ts).toLocaleString()
  }
  catch {
    return ts
  }
}

function onDismiss() {
  clearUploadedComparison()
  navigateTo('/')
}
</script>
