// Generated by Copilot
// GET /api/dates — returns sorted list of available date folders
// listDates is auto-imported from server/utils/dataAdapter
export default defineEventHandler(async () => {
  return await listDates()
})
