// Generated by Copilot
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss'],
  tailwindcss: {
    cssPath: '~/assets/css/tailwind.css',
  },
  runtimeConfig: {
    // Server-only keys — set via environment variables
    // DATA_SOURCE: 'local' (default) | 's3'
    dataSource: process.env.DATA_SOURCE ?? 'local',
    // S3 settings (only required when DATA_SOURCE=s3)
    s3Bucket: process.env.S3_BUCKET ?? '',
    s3Region: process.env.S3_REGION ?? 'us-east-1',
    // Optional key prefix inside the bucket, e.g. 'data/'
    s3Prefix: process.env.S3_PREFIX ?? '',
  },
})
