<!-- Generated by Copilot -->
<!-- BaseTabs: generic tab container — receives tab definitions + renders slot content -->
<template>
  <div>
    <!-- Tab strip -->
    <div class="border-b border-gray-200">
      <nav class="-mb-px flex space-x-1" aria-label="Tabs">
        <button
          v-for="tab in tabs"
          :key="tab.key"
          type="button"
          :class="[
            'px-4 py-2.5 text-sm font-medium border-b-2 transition-colors',
            active === tab.key
              ? 'border-blue-600 text-blue-700'
              : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300',
          ]"
          @click="active = tab.key"
        >
          {{ tab.label }}
        </button>
      </nav>
    </div>

    <!-- Tab panels -->
    <div class="pt-6">
      <slot :active="active" />
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  tabs: { key: string; label: string }[]
  defaultTab?: string
}>()

const active = ref(props.defaultTab ?? props.tabs[0]?.key ?? '')
</script>
