<!-- Generated by Copilot -->
<!-- CellValue: renders a value + optional sub-label in a source colour -->
<template>
  <div class="flex flex-col items-center gap-0.5">
    <span
      v-if="val != null"
      :class="['font-mono font-semibold text-sm', colorClass]"
    >{{ val }}</span>
    <span v-else class="text-gray-300 text-sm select-none">—</span>
    <span v-if="sub && val != null" class="text-xs text-gray-400 leading-tight text-center max-w-[140px]">{{ sub }}</span>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  val?: string | null
  sub?: string | null
  color?: 'purple' | 'blue' | 'teal'
}>()

const colorClass = computed(() => {
  switch (props.color) {
    case 'purple': return 'text-purple-800'
    case 'teal': return 'text-teal-800'
    default: return 'text-blue-800'
  }
})
</script>
