<!-- Generated by Copilot -->
<!--
  ComparisonMatrix: the core audit component.
  Displays ALL comparable data points from GPP, SEC, and Website side-by-side.
  Organised into sections: per-class (NAV, Distribution, Performance) and fund-level (Shares, Dates).
-->
<template>
  <div class="space-y-8">

    <!-- Source legend -->
    <div class="flex flex-wrap gap-3 text-xs">
      <span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-purple-100 text-purple-800 font-medium">
        <span class="w-2 h-2 rounded-full bg-purple-500 inline-block" /> GPP
      </span>
      <span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-blue-100 text-blue-800 font-medium">
        <span class="w-2 h-2 rounded-full bg-blue-500 inline-block" /> SEC Filing
      </span>
      <span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-teal-100 text-teal-800 font-medium">
        <span class="w-2 h-2 rounded-full bg-teal-500 inline-block" /> Fund Website
      </span>
      <span class="ml-auto text-gray-400 italic self-center">
        GPP report date: {{ d.gpp_data.report_date ?? '—' }}
        &nbsp;·&nbsp; SEC filing: {{ d.sec_filing.filing_date ?? '—' }}
        &nbsp;·&nbsp; Website extracted: {{ fmtTs(websiteExtractedAt) }}
      </span>
    </div>

    <!-- ── Per-class section ── -->
    <div>
      <h2 class="text-base font-semibold text-gray-700 mb-3 flex items-center gap-2">
        <span class="w-1 h-5 rounded bg-blue-500 inline-block" />
        Per Share Class Comparison
      </h2>

      <!-- Class tabs -->
      <div class="flex gap-1 mb-0 border-b border-gray-200">
        <button
          v-for="cls in shareClasses"
          :key="cls"
          type="button"
          :class="[
            'px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors',
            activeClass === cls
              ? 'border-blue-600 text-blue-700'
              : 'border-transparent text-gray-500 hover:text-gray-700',
          ]"
          @click="activeClass = cls"
        >{{ cls }}</button>
      </div>

      <div class="rounded-b-lg rounded-tr-lg border border-gray-200 overflow-hidden">
        <table class="min-w-full text-sm">
          <thead>
            <tr class="bg-gray-50 divide-x divide-gray-200">
              <th class="px-4 py-3 text-left font-semibold text-gray-600 w-48">Data Point</th>
              <th class="px-4 py-3 text-center font-semibold text-purple-700 w-52">
                <span class="flex items-center justify-center gap-1">
                  <span class="w-2 h-2 rounded-full bg-purple-400 inline-block" />GPP
                </span>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-blue-700 w-52">
                <span class="flex items-center justify-center gap-1">
                  <span class="w-2 h-2 rounded-full bg-blue-400 inline-block" />SEC
                </span>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-teal-700 w-52">
                <span class="flex items-center justify-center gap-1">
                  <span class="w-2 h-2 rounded-full bg-teal-400 inline-block" />Website
                </span>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-gray-600 w-32">Status</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100 bg-white">
            <template v-for="row in classRows(activeClass)" :key="row.label">
              <tr
                :class="[
                  'divide-x divide-gray-100 transition-colors',
                  row.highlight ? 'bg-yellow-50 hover:bg-yellow-100' : 'hover:bg-gray-50',
                ]"
              >
                <td class="px-4 py-3 font-medium text-gray-700">
                  {{ row.label }}
                  <span v-if="row.note" class="block text-xs text-gray-400 font-normal">{{ row.note }}</span>
                </td>
                <td class="px-4 py-3 text-center">
                  <CellValue :val="row.gpp" :sub="row.gppSub" color="purple" />
                </td>
                <td class="px-4 py-3 text-center">
                  <CellValue :val="row.sec" :sub="row.secSub" color="blue" />
                </td>
                <td class="px-4 py-3 text-center">
                  <CellValue :val="row.web" :sub="row.webSub" color="teal" />
                </td>
                <td class="px-4 py-3 text-center">
                  <StatusBadge :status="row.status" />
                </td>
              </tr>
            </template>
          </tbody>
        </table>
      </div>
    </div>

    <!-- ── Fund-level section ── -->
    <div>
      <h2 class="text-base font-semibold text-gray-700 mb-3 flex items-center gap-2">
        <span class="w-1 h-5 rounded bg-teal-500 inline-block" />
        Fund-Level Data Points
      </h2>

      <div class="rounded-lg border border-gray-200 overflow-hidden">
        <table class="min-w-full text-sm">
          <thead>
            <tr class="bg-gray-50 divide-x divide-gray-200">
              <th class="px-4 py-3 text-left font-semibold text-gray-600 w-48">Data Point</th>
              <th class="px-4 py-3 text-center font-semibold text-purple-700 w-52">
                <span class="flex items-center justify-center gap-1"><span class="w-2 h-2 rounded-full bg-purple-400 inline-block" />GPP</span>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-blue-700 w-52">
                <span class="flex items-center justify-center gap-1"><span class="w-2 h-2 rounded-full bg-blue-400 inline-block" />SEC</span>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-teal-700 w-52">
                <span class="flex items-center justify-center gap-1"><span class="w-2 h-2 rounded-full bg-teal-400 inline-block" />Website</span>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-gray-600 w-32">Status</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100 bg-white">
            <tr
              v-for="row in fundRows"
              :key="row.label"
              :class="[
                'divide-x divide-gray-100 transition-colors',
                row.highlight ? 'bg-yellow-50 hover:bg-yellow-100' : 'hover:bg-gray-50',
              ]"
            >
              <td class="px-4 py-3 font-medium text-gray-700">
                {{ row.label }}
                <span v-if="row.note" class="block text-xs text-gray-400 font-normal">{{ row.note }}</span>
              </td>
              <td class="px-4 py-3 text-center"><CellValue :val="row.gpp" :sub="row.gppSub" color="purple" /></td>
              <td class="px-4 py-3 text-center"><CellValue :val="row.sec" :sub="row.secSub" color="blue" /></td>
              <td class="px-4 py-3 text-center"><CellValue :val="row.web" :sub="row.webSub" color="teal" /></td>
              <td class="px-4 py-3 text-center"><StatusBadge :status="row.status" /></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- ── GPP section availability ── -->
    <div>
      <h2 class="text-base font-semibold text-gray-700 mb-3 flex items-center gap-2">
        <span class="w-1 h-5 rounded bg-purple-500 inline-block" />
        GPP Section Availability
      </h2>
      <div class="flex flex-wrap gap-2">
        <span
          v-for="sec in knownGppSections"
          :key="sec"
          :class="[
            'inline-flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-full border font-mono font-medium',
            d.gpp_data.sections[sec]
              ? 'bg-green-50 border-green-300 text-green-800'
              : 'bg-red-50 border-red-300 text-red-700',
          ]"
        >
          <span :class="d.gpp_data.sections[sec] ? 'text-green-500' : 'text-red-400'">
            {{ d.gpp_data.sections[sec] ? '✓' : '✗' }}
          </span>
          {{ sec }}
        </span>
      </div>
    </div>

  </div>
</template>

<script setup lang="ts">
import type { ComparisonDetail } from '~/types/comparison'

const props = defineProps<{ d: ComparisonDetail }>()

// ── Helpers ────────────────────────────────────────────────────────────────

function fmtNav(v: number | null | undefined) {
  return v != null ? `$${v.toFixed(4)}` : null
}
function fmtPct(v: number | null | undefined) {
  return v != null ? `${v.toFixed(2)}%` : null
}
function fmtNum(v: number | null | undefined) {
  return v != null ? v.toLocaleString() : null
}
function fmtTs(ts: string | null | undefined) {
  if (!ts) return '—'
  try { return new Date(ts).toLocaleDateString() } catch { return ts }
}

/** Compare up to 3 non-null values; return status */
function cmp(...vals: (string | number | null | undefined)[]): 'match' | 'mismatch' | 'unavailable' {
  const present = vals.filter(v => v != null && v !== '—' && v !== '')
  if (present.length < 2) return 'unavailable'
  // For numbers, compare with tolerance
  const nums = present.filter(v => typeof v === 'number') as number[]
  if (nums.length === present.length) {
    const min = Math.min(...nums), max = Math.max(...nums)
    return (max - min) < 0.001 ? 'match' : 'mismatch'
  }
  return new Set(present.map(String)).size === 1 ? 'match' : 'mismatch'
}

// ── GPP latest values (per-class section format) ────────────────────────
// Each section entry is { PerformanceId, Date, "Class X": value }

function gppLatestForClass(section: string, cls: string): { value: number | null; date: string | null } {
  const pts = props.d.gpp_data?.sections?.[section]
  if (!pts?.length) return { value: null, date: null }
  const classEntries = pts.filter(p => p[cls] != null)
  if (!classEntries.length) return { value: null, date: null }
  const last = classEntries[classEntries.length - 1]
  if (!last) return { value: null, date: null }
  return { value: (last[cls] as number) ?? null, date: last.Date ?? null }
}

// Known GPP sections (replaces expected_sections field removed from schema)
const knownGppSections = ['Price', 'Dividend', 'CapitalGain', 'DailyDividend', 'ClassTNA']

// ── Website latest dividend per class ────────────────────────────────────

function webDividend(cls: string): number | null {
  const entries = props.d.website?.share_classes?.[cls]?.historical_nav ?? []
  // Find the most recent "Dividend Distribution" year entry
  const divEntries = entries.filter(e => e.date?.includes('Dividend Distribution'))
  if (!divEntries.length) return null
  // Grab the first (most recent year grouping)
  return divEntries[0]?.nav ?? null
}

// ── Share classes ─────────────────────────────────────────────────────────

const shareClasses = computed(() => Object.keys(props.d.comparison?.per_class ?? {}))
const activeClass = ref(shareClasses.value[0] ?? '')

// ── Website extracted timestamp ───────────────────────────────────────────

const websiteExtractedAt = computed(() => {
  const first = Object.values(props.d.website?.share_classes ?? {})[0] as { extraction_timestamp?: string | null } | undefined
  return first?.extraction_timestamp ?? undefined
})

// ── Per-class rows ────────────────────────────────────────────────────────

interface Row {
  label: string
  note?: string
  gpp: string | null
  gppSub?: string | null
  sec: string | null
  secSub?: string | null
  web: string | null
  webSub?: string | null
  status: 'match' | 'mismatch' | 'unavailable'
  highlight: boolean
}

function classRows(cls: string): Row[] {
  const secExt = props.d.sec_filing?.extraction
  const webCls = props.d.website?.share_classes?.[cls]
  const perfCls = props.d.performance?.per_class?.[cls]
  const distCls = props.d.sec_filing?.extraction?.distribution_data?.per_class?.[cls]
  const sharesCls = props.d.shares_outstanding?.per_class?.[cls]

  const gppPriceEntry = gppLatestForClass('Price', cls)
  const gppDivEntry = gppLatestForClass('Dividend', cls)
  const gppTnaEntry = gppLatestForClass('ClassTNA', cls)

  // Prefer gpp_comparison (pre-computed by pipeline) when values are non-null
  const gppCmp = props.d.gpp_comparison?.nav_per_class?.[cls]
  const navGpp = gppCmp?.gpp_price ?? gppPriceEntry.value
  const navGppDate = gppCmp?.gpp_price_date ?? gppPriceEntry.date
  const navSec = secExt?.nav_per_share?.[cls] ?? null
  const navWeb = webCls?.nav_per_share ?? null

  const divGpp = gppDivEntry.value
  const divSec = distCls?.net_distribution ?? null
  const divWeb = webDividend(cls)

  const tnaGpp = gppTnaEntry.value
  const tnaSec = (secExt?.tna_per_class as Record<string, number | null>)?.[cls] ?? null
  const tnaWeb = perfCls?.tna ?? null

  const rows: Row[] = [
    {
      label: 'NAV per Share',
      gpp: fmtNav(navGpp),
      gppSub: navGppDate,
      sec: fmtNav(navSec),
      secSub: secExt?.nav_date ?? null,
      web: fmtNav(navWeb),
      webSub: webCls?.nav_date ?? null,
      status: cmp(navGpp, navSec, navWeb),
      highlight: cmp(navGpp, navSec, navWeb) === 'mismatch',
    },
    {
      label: 'NAV As-of Date',
      note: 'Date difference explains NAV mismatch',
      gpp: navGppDate,
      sec: secExt?.nav_date ?? null,
      web: webCls?.nav_date ?? null,
      status: cmp(navGppDate, secExt?.nav_date, webCls?.nav_date),
      highlight: false,
    },
    {
      label: 'Dividend per Share',
      note: 'Net distribution / latest monthly dividend',
      gpp: fmtNav(divGpp),
      gppSub: gppDivEntry.date,
      sec: fmtNav(divSec),
      secSub: props.d.distributions?.payment_date ?? null,
      web: fmtNav(divWeb),
      webSub: 'website historical',
      status: cmp(divGpp, divSec, divWeb),
      highlight: cmp(divGpp, divSec, divWeb) === 'mismatch',
    },
    {
      label: 'Annualized Distribution Rate',
      gpp: null,
      sec: null,
      web: fmtPct(webCls?.annualized_distribution_rate),
      status: 'unavailable',
      highlight: false,
    },
    {
      label: 'Total Net Assets (TNA)',
      gpp: fmtNum(tnaGpp),
      gppSub: gppTnaEntry.date,
      sec: fmtNum(tnaSec),
      web: fmtNum(tnaWeb),
      status: cmp(tnaGpp, tnaSec, tnaWeb),
      highlight: cmp(tnaGpp, tnaSec, tnaWeb) === 'mismatch',
    },
    {
      label: 'Shares Issued',
      gpp: null,
      sec: fmtNum(props.d.shares_outstanding?.per_class?.[cls]?.shares_issued),
      secSub: sharesCls ? `${(sharesCls.percent_of_total ?? 0).toFixed(4)}% of total` : null,
      web: null,
      status: 'unavailable',
      highlight: false,
    },
  ]

  return rows
}

// ── Fund-level rows ────────────────────────────────────────────────────────

const fundRows = computed<Row[]>(() => {
  const dist = props.d.distributions
  const secDist = props.d.sec_filing?.extraction?.distribution_data

  return [
    {
      label: 'Distribution Declaration Date',
      gpp: null,
      sec: dist?.declaration_date ?? null,
      web: null,
      status: 'unavailable',
      highlight: false,
    },
    {
      label: 'Distribution Record Date',
      gpp: null,
      sec: dist?.record_date ?? null,
      web: null,
      status: 'unavailable',
      highlight: false,
    },
    {
      label: 'Distribution Payment Date',
      gpp: null,
      sec: dist?.payment_date ?? null,
      web: null,
      status: 'unavailable',
      highlight: false,
    },
    {
      label: 'Total Shares Issued',
      gpp: null,
      sec: fmtNum(secDist?.total_shares_issued),
      web: null,
      status: 'unavailable',
      highlight: false,
    },
    {
      label: 'SEC Filing Type',
      gpp: null,
      sec: props.d.sec_filing?.filing_type ?? null,
      secSub: props.d.sec_filing?.filing_date ?? null,
      web: null,
      status: 'unavailable',
      highlight: false,
    },
    {
      label: 'GPP Data Source',
      gpp: (() => {
        const ds = props.d.gpp_data?.data_source
        if (ds == null) return null
        if (typeof ds === 'object') return Object.values(ds as Record<string, string>).join(', ')
        return String(ds)
      })(),
      gppSub: `status: ${props.d.gpp_data?.status ?? '—'}`,
      sec: null,
      web: null,
      status: 'unavailable',
      highlight: false,
    },
    {
      label: 'GPP Performance IDs',
      gpp: (() => {
        const ids = props.d.gpp_data?.performance_ids_by_class ?? {}
        const entries = Object.entries(ids).map(([k, v]) => `${k}: ${v}`)
        return entries.length ? entries.join(' · ') : null
      })(),
      sec: null,
      web: null,
      status: 'unavailable',
      highlight: false,
    },
    {
      label: 'Website URL',
      gpp: null,
      sec: null,
      web: props.d.website?.url ?? null,
      status: 'unavailable',
      highlight: false,
    },
  ]
})
</script>
