<!-- Generated by Copilot -->
<!-- DataRow: labelled key-value row used across detail tabs -->
<template>
  <div class="flex items-start justify-between py-2 border-b border-gray-100 last:border-0">
    <dt class="text-sm text-gray-500 min-w-[180px]">{{ label }}</dt>
    <dd class="text-sm font-medium text-gray-900 text-right">
      <slot>{{ value ?? '—' }}</slot>
    </dd>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  label: string
  value?: string | number | null
}>()
</script>
