<!-- Generated by Copilot -->
<!-- StatusBadge: pill badge with colour-coded status -->
<template>
  <span
    :class="[
      'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium capitalize',
      colourClass,
    ]"
  >
    {{ label || status }}
  </span>
</template>

<script setup lang="ts">
const props = defineProps<{
  status: string
  label?: string
}>()

const colourClass = computed(() => {
  switch (props.status?.toLowerCase()) {
    case 'match': return 'bg-green-100 text-green-800'
    case 'ok': return 'bg-green-100 text-green-800'
    case 'mismatch': return 'bg-yellow-100 text-yellow-800'
    case 'error': return 'bg-red-100 text-red-800'
    default: return 'bg-gray-100 text-gray-600'
  }
})
</script>
