<!-- Generated by Copilot -->
<!-- Modal for uploading a ComparisonDetail JSON file for ad-hoc preview.
     Parses and validates the file client-side, then routes to /comparison/preview. -->
<template>
  <!-- Backdrop -->
  <Teleport to="body">
    <div
      class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"
      @click.self="$emit('close')"
    >
      <div class="bg-white rounded-2xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden">
        <!-- Header -->
        <div class="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <div>
            <h2 class="text-lg font-semibold text-gray-900">Upload Comparison File</h2>
            <p class="text-xs text-gray-500 mt-0.5">Load a JSON result file for ad-hoc review</p>
          </div>
          <button
            class="text-gray-400 hover:text-gray-600 transition-colors p-1 rounded-lg hover:bg-gray-100"
            aria-label="Close"
            @click="$emit('close')"
          >
            <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <!-- Body -->
        <div class="px-6 py-5 space-y-4">
          <!-- Drop zone -->
          <div
            :class="[
              'relative flex flex-col items-center justify-center rounded-xl border-2 border-dashed px-6 py-10 transition-colors cursor-pointer',
              isDragging
                ? 'border-blue-400 bg-blue-50'
                : 'border-gray-300 bg-gray-50 hover:border-blue-400 hover:bg-blue-50',
            ]"
            @dragover.prevent="isDragging = true"
            @dragleave.prevent="isDragging = false"
            @drop.prevent="onDrop"
            @click="fileInput?.click()"
          >
            <svg class="h-10 w-10 text-blue-400 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
            </svg>
            <p class="text-sm font-medium text-gray-700">
              <span class="text-blue-600">Click to browse</span> or drag &amp; drop
            </p>
            <p class="text-xs text-gray-400 mt-1">Accepts <code class="font-mono bg-gray-100 px-1 rounded">*.json</code> — ComparisonDetail format</p>

            <!-- Hidden file input -->
            <input
              ref="fileInput"
              type="file"
              accept=".json,application/json"
              class="sr-only"
              @change="onFileChange"
            />
          </div>

          <!-- Selected file name -->
          <div v-if="selectedFileName" class="flex items-center gap-2 text-sm text-gray-600 bg-gray-50 rounded-lg px-3 py-2 border border-gray-200">
            <svg class="h-4 w-4 text-blue-500 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span class="truncate font-mono">{{ selectedFileName }}</span>
          </div>

          <!-- Error -->
          <div v-if="parseError" class="flex items-start gap-2 text-sm text-red-700 bg-red-50 border border-red-200 rounded-lg px-3 py-3">
            <svg class="h-4 w-4 text-red-500 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
            <div>
              <p class="font-medium">Invalid file</p>
              <p class="text-xs mt-0.5">{{ parseError }}</p>
            </div>
          </div>

          <!-- Format hint -->
          <details class="text-xs text-gray-400">
            <summary class="cursor-pointer hover:text-gray-600 transition-colors">Expected file format</summary>
            <p class="mt-1 leading-relaxed pl-2 border-l-2 border-gray-200">
              A JSON file containing a <code class="font-mono">ComparisonDetail</code> object with top-level keys:
              <code class="font-mono">fund</code>, <code class="font-mono">comparison</code>, and
              <code class="font-mono">sec_filing</code>.
            </p>
          </details>
        </div>

        <!-- Footer -->
        <div class="flex items-center justify-end gap-3 px-6 py-4 border-t border-gray-100 bg-gray-50">
          <button
            class="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors"
            @click="$emit('close')"
          >
            Cancel
          </button>
          <button
            :disabled="!parsedData || isLoading"
            :class="[
              'px-5 py-2 text-sm font-semibold rounded-lg transition-colors',
              parsedData && !isLoading
                ? 'bg-blue-600 text-white hover:bg-blue-700'
                : 'bg-gray-200 text-gray-400 cursor-not-allowed',
            ]"
            @click="openPreview"
          >
            <span v-if="isLoading" class="flex items-center gap-2">
              <svg class="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
              </svg>
              Loading…
            </span>
            <span v-else>Open Preview →</span>
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import type { ComparisonDetail } from '~/types/comparison'

const emit = defineEmits<{ (e: 'close'): void }>()

const { setUploadedComparison } = useUploadedComparison()

const fileInput = ref<HTMLInputElement | null>(null)
const isDragging = ref(false)
const isLoading = ref(false)
const selectedFileName = ref('')
const parseError = ref('')
const parsedData = ref<ComparisonDetail | null>(null)

function onDrop(event: DragEvent) {
  isDragging.value = false
  const file = event.dataTransfer?.files[0]
  if (file) processFile(file)
}

function onFileChange(event: Event) {
  const file = (event.target as HTMLInputElement).files?.[0]
  if (file) processFile(file)
}

function processFile(file: File) {
  parseError.value = ''
  parsedData.value = null
  selectedFileName.value = file.name

  if (!file.name.endsWith('.json') && file.type !== 'application/json') {
    parseError.value = 'Only .json files are accepted.'
    return
  }

  const reader = new FileReader()
  reader.onload = (e) => {
    try {
      const raw = e.target?.result as string
      const parsed = JSON.parse(raw) as ComparisonDetail

      // Basic shape validation
      if (!parsed.fund || !parsed.comparison || !parsed.sec_filing) {
        parseError.value =
          'File does not look like a ComparisonDetail — missing one or more of: fund, comparison, sec_filing.'
        return
      }

      parsedData.value = parsed
    }
    catch (err) {
      parseError.value = err instanceof SyntaxError
        ? `JSON syntax error: ${err.message}`
        : 'Could not parse file. Make sure it is valid JSON.'
    }
  }
  reader.onerror = () => {
    parseError.value = 'Failed to read the file. Please try again.'
  }
  reader.readAsText(file)
}

function openPreview() {
  if (!parsedData.value) return
  isLoading.value = true
  setUploadedComparison(parsedData.value)
  navigateTo('/comparison/preview')
  emit('close')
}
</script>
