<!-- Generated by Copilot -->
<!-- Detailed comparison view: fund header + 4-tab layout -->
<template>
  <div class="space-y-6">
    <!-- Back link -->
    <NuxtLink to="/" class="inline-flex items-center gap-1 text-sm text-blue-600 hover:text-blue-800">
      ← Back to Dashboard
    </NuxtLink>

    <!-- Loading -->
    <div v-if="pending" class="flex items-center gap-2 text-gray-400 text-sm py-12 justify-center">
      <svg class="animate-spin h-5 w-5 text-blue-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
      </svg>
      Loading comparison…
    </div>

    <!-- Error -->
    <div v-else-if="error" class="bg-red-50 border border-red-200 rounded-lg p-4 text-sm text-red-700">
      Failed to load comparison: {{ error.message }}
    </div>

    <!-- Main content -->
    <template v-else-if="detail">
      <!-- Fund header card -->
      <div class="bg-white rounded-xl border border-gray-200 p-6">
        <div class="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 class="text-xl font-bold text-gray-900">{{ detail.fund.name }}</h1>
            <p class="mt-1 text-sm text-gray-500">
              CIK: <span class="font-mono text-gray-700">{{ detail.fund.cik }}</span>
              &nbsp;·&nbsp;
              Generated: {{ fmtTs(detail.fund.generated_at) }}
            </p>
          </div>
          <StatusBadge :status="overallStatus" class="text-sm px-3 py-1" />
        </div>
      </div>

      <!-- Tabbed detail -->
      <div class="bg-white rounded-xl border border-gray-200 p-6">
        <BaseTabs :tabs="tabs" default-tab="matrix">
          <template #default="{ active }">
            <!-- Side-by-side comparison matrix (primary view) -->
            <div v-show="active === 'matrix'">
              <ComparisonMatrix :d="detail" />
            </div>

            <!-- NAV Tab -->
            <div v-show="active === 'nav'">
              <TabNavTab :comparison="detail.comparison" :performance="detail.performance" />
            </div>

            <!-- Distributions Tab -->
            <div v-show="active === 'distributions'">
              <TabDistributionsTab :distributions="detail.distributions" />
            </div>

            <!-- Shares Tab -->
            <div v-show="active === 'shares'">
              <TabSharesTab :shares="detail.shares_outstanding" />
            </div>

            <!-- GPP Data Tab -->
            <div v-show="active === 'gpp'">
              <TabGppTab :gpp="detail.gpp_data" />
            </div>
          </template>
        </BaseTabs>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
const route = useRoute()
const date = route.params.date as string
const cik = route.params.cik as string

const { data: detail, pending, error } = useComparisonDetail(date, cik)

const tabs = [
  { key: 'matrix', label: '⚖️ Side-by-Side Comparison' },
  { key: 'nav', label: 'NAV Detail' },
  { key: 'distributions', label: 'Distributions' },
  { key: 'shares', label: 'Shares Outstanding' },
  { key: 'gpp', label: 'GPP Data' },
]

// Derive overall status from comparison per_class statuses
const overallStatus = computed(() => {
  const classes = Object.values(detail.value?.comparison?.per_class ?? {})
  if (classes.length === 0) return 'unknown'
  if (classes.some(c => c.status === 'error')) return 'error'
  if (classes.some(c => c.status === 'mismatch')) return 'mismatch'
  if (classes.every(c => c.status === 'match')) return 'match'
  return 'ok'
})

function fmtTs(ts: string) {
  try {
    return new Date(ts).toLocaleString()
  } catch {
    return ts
  }
}
</script>
