// Generated by Copilot
// Composable: useComparisons — fetches CIK list for a given date
import type { CIKListEntry } from '~/types/comparison'

export function useComparisons(date: Ref<string>) {
  const { data, pending, error, refresh } = useFetch<CIKListEntry[]>(
    () => `/api/comparisons/${date.value}`,
    { watch: [date] }
  )
  return { data, pending, error, refresh }
}
