// Generated by Copilot
// Composable: useComparisonDetail — fetches full comparison for a date + CIK
import type { ComparisonDetail } from '~/types/comparison'

export function useComparisonDetail(date: string, cik: string) {
  const { data, pending, error } = useFetch<ComparisonDetail>(
    `/api/comparison/${date}/${cik}`
  )
  return { data, pending, error }
}
