// Generated by Copilot
// Ephemeral client-side state for a ComparisonDetail uploaded by the user.
// Stored in Nuxt useState so it survives client-side route navigation.
// Data is cleared when the tab is refreshed (intentional — preview only).

import type { ComparisonDetail } from '~/types/comparison'

export function useUploadedComparison() {
  const uploadedComparison = useState<ComparisonDetail | null>('uploadedComparison', () => null)

  function setUploadedComparison(data: ComparisonDetail) {
    uploadedComparison.value = data
  }

  function clearUploadedComparison() {
    uploadedComparison.value = null
  }

  return { uploadedComparison, setUploadedComparison, clearUploadedComparison }
}
