<!-- Generated by Copilot -->
<template>
  <div class="min-h-screen bg-gray-50 text-gray-900">
    <NuxtRouteAnnouncer />
    <!-- Top navigation bar -->
    <header class="bg-white border-b border-gray-200 shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
        <NuxtLink to="/" class="flex items-center gap-2 font-semibold text-blue-700 hover:text-blue-900">
          <span class="text-lg">📊</span>
          <span>PPC Audit Dashboard</span>
        </NuxtLink>
        <span class="text-xs text-gray-400">Data Consistency Monitor</span>
      </div>
    </header>
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <NuxtPage />
    </main>
  </div>
</template>
