<!-- Generated by Copilot -->
<!-- Dashboard list page: date picker + search + status filter + CIK table -->
<template>
  <div class="space-y-6">
    <!-- Page header -->
    <div class="flex flex-wrap items-start justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Comparison Dashboard</h1>
        <p class="mt-1 text-sm text-gray-500">
          Daily cross-source data consistency checks (GPP · SEC · Fund Website)
        </p>
      </div>
      <button
        class="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors shadow-sm"
        @click="showUploadModal = true"
      >
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
        </svg>
        Upload File
      </button>
    </div>

    <!-- Upload modal -->
    <UploadModal v-if="showUploadModal" @close="showUploadModal = false" />

    <!-- Filters row -->
    <div class="bg-white rounded-xl border border-gray-200 p-4 flex flex-wrap gap-4 items-end">
      <!-- Date picker -->
      <div class="flex flex-col gap-1">
        <label class="text-xs font-medium text-gray-500 uppercase tracking-wide">Date</label>
        <select
          v-model="selectedDate"
          class="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none min-w-[160px]"
        >
          <option v-for="d in dates" :key="d" :value="d">{{ d }}</option>
        </select>
      </div>

      <!-- Search -->
      <div class="flex flex-col gap-1 flex-1 min-w-[200px]">
        <label class="text-xs font-medium text-gray-500 uppercase tracking-wide">Search</label>
        <input
          v-model="search"
          type="text"
          placeholder="Fund name or CIK…"
          class="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
        />
      </div>

      <!-- Status filter -->
      <div class="flex flex-col gap-1">
        <label class="text-xs font-medium text-gray-500 uppercase tracking-wide">Status</label>
        <select
          v-model="statusFilter"
          class="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
        >
          <option value="">All</option>
          <option value="match">Match</option>
          <option value="mismatch">Mismatch</option>
          <option value="error">Error</option>
          <option value="ok">Ok</option>
        </select>
      </div>
    </div>

    <!-- Loading / error states -->
    <div v-if="pending" class="flex items-center gap-2 text-gray-400 text-sm py-8 justify-center">
      <svg class="animate-spin h-4 w-4 text-blue-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
      </svg>
      Loading comparisons…
    </div>
    <div v-else-if="error" class="bg-red-50 border border-red-200 rounded-lg p-4 text-sm text-red-700">
      Failed to load comparisons for {{ selectedDate }}: {{ error.message }}
    </div>

    <!-- Table -->
    <div v-else class="bg-white rounded-xl border border-gray-200 overflow-hidden">
      <div class="px-4 py-3 border-b border-gray-100 flex items-center justify-between">
        <span class="text-sm text-gray-500">{{ filtered.length }} result{{ filtered.length !== 1 ? 's' : '' }}</span>
      </div>

      <div v-if="filtered.length === 0" class="py-12 text-center text-sm text-gray-400 italic">
        No comparisons match your filters.
      </div>

      <table v-else class="min-w-full divide-y divide-gray-100 text-sm">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Fund Name</th>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">CIK</th>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Date</th>
            <th class="px-4 py-3 text-center font-semibold text-gray-600">Status</th>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Timestamp</th>
            <th class="px-4 py-3" />
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-50">
          <tr
            v-for="entry in filtered"
            :key="entry.cik"
            class="hover:bg-blue-50 cursor-pointer transition-colors"
            @click="navigate(entry.cik)"
          >
            <td class="px-4 py-3 font-medium text-gray-900">{{ entry.fund_name }}</td>
            <td class="px-4 py-3 text-gray-500 font-mono text-xs">{{ entry.cik }}</td>
            <td class="px-4 py-3 text-gray-500">{{ selectedDate }}</td>
            <td class="px-4 py-3 text-center">
              <StatusBadge :status="entry.overall_status" />
            </td>
            <td class="px-4 py-3 text-gray-400 text-xs">{{ fmtTimestamp(entry.timestamp) }}</td>
            <td class="px-4 py-3 text-right">
              <NuxtLink
                :to="`/comparison/${selectedDate}/${entry.cik}`"
                class="text-blue-600 hover:text-blue-800 font-medium text-xs"
                @click.stop
              >View →</NuxtLink>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { CIKListEntry } from '~/types/comparison'

const router = useRouter()
const showUploadModal = ref(false)

// Load available dates
const { data: dates } = await useFetch<string[]>('/api/dates')

const selectedDate = ref(dates.value?.[0] ?? '')
const search = ref('')
const statusFilter = ref('')

// Load CIK list for selected date
const { data, pending, error } = useComparisons(selectedDate)

const filtered = computed<CIKListEntry[]>(() => {
  if (!data.value) return []
  return data.value.filter(e => {
    const matchesSearch =
      !search.value ||
      e.fund_name.toLowerCase().includes(search.value.toLowerCase()) ||
      e.cik.includes(search.value)
    const matchesStatus = !statusFilter.value || e.overall_status === statusFilter.value
    return matchesSearch && matchesStatus
  })
})

function navigate(cik: string) {
  router.push(`/comparison/${selectedDate.value}/${cik}`)
}

function fmtTimestamp(ts: string) {
  try {
    return new Date(ts).toLocaleString()
  } catch {
    return ts
  }
}
</script>
