// Generated by Copilot
// GET /api/comparisons/:date — returns CIK list for a date
// listComparisons is auto-imported from server/utils/dataAdapter
export default defineEventHandler(async (event) => {
  const date = getRouterParam(event, 'date')!
  return await listComparisons(date)
})
