<!-- Generated by Copilot -->
<!-- DistributionsTab: declaration/record/payment dates + per-class gross/fee/net -->
<template>
  <div class="space-y-6">
    <!-- Dates -->
    <div class="grid grid-cols-3 gap-4">
      <div class="bg-blue-50 rounded-lg p-4 text-center">
        <p class="text-xs text-blue-600 font-medium uppercase tracking-wide">Declaration Date</p>
        <p class="mt-1 text-sm font-semibold text-blue-900">{{ distributions.declaration_date ?? '—' }}</p>
      </div>
      <div class="bg-blue-50 rounded-lg p-4 text-center">
        <p class="text-xs text-blue-600 font-medium uppercase tracking-wide">Record Date</p>
        <p class="mt-1 text-sm font-semibold text-blue-900">{{ distributions.record_date ?? '—' }}</p>
      </div>
      <div class="bg-blue-50 rounded-lg p-4 text-center">
        <p class="text-xs text-blue-600 font-medium uppercase tracking-wide">Payment Date</p>
        <p class="mt-1 text-sm font-semibold text-blue-900">{{ distributions.payment_date ?? '—' }}</p>
      </div>
    </div>

    <!-- Per-class table -->
    <div class="overflow-x-auto rounded-lg border border-gray-200">
      <table class="min-w-full divide-y divide-gray-200 text-sm">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Share Class</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Gross Distribution</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Servicing Fee</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Net Distribution</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-100 bg-white">
          <tr v-for="(cls, name) in distributions.per_class" :key="name" class="hover:bg-gray-50">
            <td class="px-4 py-3 font-medium text-gray-900">{{ name }}</td>
            <td class="px-4 py-3 text-right">{{ fmt(cls.gross_distribution) }}</td>
            <td class="px-4 py-3 text-right">{{ fmt(cls.servicing_fee) }}</td>
            <td class="px-4 py-3 text-right font-medium">{{ fmt(cls.net_distribution) }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ComparisonDetail } from '~/types/comparison'

defineProps<{
  distributions: ComparisonDetail['distributions']
}>()

function fmt(v: number | null | undefined) {
  return v != null ? `$${v.toFixed(4)}` : '—'
}
</script>
