<!-- Generated by Copilot -->
<!-- DistributionsTab: declaration/record/payment dates + per-class gross/fee/net + fund-level details -->
<template>
  <div class="space-y-6">
    <!-- Dates -->
    <div class="grid grid-cols-3 gap-4">
      <div class="bg-blue-50 rounded-lg p-4 text-center">
        <p class="text-xs text-blue-600 font-medium uppercase tracking-wide">Declaration Date</p>
        <p class="mt-1 text-sm font-semibold text-blue-900">{{ distributions.declaration_date ?? '—' }}</p>
      </div>
      <div class="bg-blue-50 rounded-lg p-4 text-center">
        <p class="text-xs text-blue-600 font-medium uppercase tracking-wide">Record Date</p>
        <p class="mt-1 text-sm font-semibold text-blue-900">{{ distributions.record_date ?? '—' }}</p>
      </div>
      <div class="bg-blue-50 rounded-lg p-4 text-center">
        <p class="text-xs text-blue-600 font-medium uppercase tracking-wide">Payment Date</p>
        <p class="mt-1 text-sm font-semibold text-blue-900">{{ distributions.payment_date ?? '—' }}</p>
      </div>
    </div>

    <!-- Per-class table -->
    <div class="overflow-x-auto rounded-lg border border-gray-200">
      <table class="min-w-full divide-y divide-gray-200 text-sm">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Share Class</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Gross Distribution</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Servicing Fee</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Net Distribution</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-100 bg-white">
          <tr v-for="(cls, name) in distributions.per_class" :key="name" class="hover:bg-gray-50">
            <td class="px-4 py-3 font-medium text-gray-900">{{ name }}</td>
            <td class="px-4 py-3 text-right">{{ fmt(cls.gross_distribution) }}</td>
            <td class="px-4 py-3 text-right">{{ fmt(cls.servicing_fee) }}</td>
            <td class="px-4 py-3 text-right font-medium">{{ fmt(cls.net_distribution) }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Fund-Level Data Points -->
    <div>
      <h2 class="text-base font-semibold text-gray-700 mb-3 flex items-center gap-2">
        <span class="w-1 h-5 rounded bg-teal-500 inline-block" />
        Fund-Level Data Points
      </h2>
      <div class="overflow-x-auto rounded-lg border border-gray-200">
        <table class="min-w-full text-sm">
          <thead>
            <tr class="bg-gray-50 divide-x divide-gray-200">
              <th class="px-4 py-3 text-left font-semibold text-gray-600 w-48">Data Point</th>
              <th class="px-4 py-3 text-center font-semibold text-purple-700 w-52">
                <span class="flex items-center justify-center gap-1">
                  <span class="w-2 h-2 rounded-full bg-purple-400 inline-block" />GPP
                </span>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-blue-700 w-52">
                <span class="flex items-center justify-center gap-1">
                  <span class="w-2 h-2 rounded-full bg-blue-400 inline-block" />SEC
                </span>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-teal-700 w-52">
                <span class="flex items-center justify-center gap-1">
                  <span class="w-2 h-2 rounded-full bg-teal-400 inline-block" />Website
                </span>
                <a
                  v-if="websiteUrl"
                  :href="websiteUrl"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="block text-xs font-normal text-teal-500 underline hover:text-teal-700 transition-colors truncate max-w-[180px] mx-auto mt-0.5"
                  :title="websiteUrl"
                >{{ websiteUrl }}</a>
              </th>
              <th class="px-4 py-3 text-center font-semibold text-gray-600 w-32">Status</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100 bg-white">
            <tr v-for="row in fundRows" :key="row.label" class="divide-x divide-gray-100 hover:bg-gray-50">
              <td class="px-4 py-3 font-medium text-gray-700">
                {{ row.label }}
                <span v-if="row.note" class="block text-xs text-gray-400 font-normal">{{ row.note }}</span>
              </td>
              <td class="px-4 py-3 text-center">
                <CellValue :val="row.gpp" :sub="row.gppSub" color="purple" />
              </td>
              <td class="px-4 py-3 text-center">
                <CellValue :val="row.sec" :sub="row.secSub" color="blue" />
              </td>
              <td class="px-4 py-3 text-center">
                <CellValue :val="row.web" :sub="row.webSub" color="teal" />
              </td>
              <td class="px-4 py-3 text-center">
                <StatusBadge :status="row.status" />
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot
import type { ComparisonDetail } from '~/types/comparison'

const props = defineProps<{
  distributions: ComparisonDetail['distributions']
  secFiling: ComparisonDetail['sec_filing']
  gppData: ComparisonDetail['gpp_data']
  websiteUrl: string | null
}>()

function fmt(v: number | null | undefined) {
  return v != null ? `$${v.toFixed(4)}` : '—'
}

function fmtNum(v: number | null | undefined) {
  return v != null ? v.toLocaleString() : null
}

interface Row {
  label: string
  note?: string
  gpp: string | null
  gppSub?: string | null
  sec: string | null
  secSub?: string | null
  web: string | null
  webSub?: string | null
  status: 'match' | 'mismatch' | 'unavailable'
}

const fundRows = computed<Row[]>(() => {
  const secDist = props.secFiling?.extraction?.distribution_data

  return [
    {
      label: 'Distribution Declaration Date',
      gpp: null,
      sec: props.distributions?.declaration_date ?? null,
      web: null,
      status: 'unavailable',
    },
    {
      label: 'Distribution Record Date',
      gpp: null,
      sec: props.distributions?.record_date ?? null,
      web: null,
      status: 'unavailable',
    },
    {
      label: 'Distribution Payment Date',
      gpp: null,
      sec: props.distributions?.payment_date ?? null,
      web: null,
      status: 'unavailable',
    },
    {
      label: 'Total Shares Issued',
      gpp: null,
      sec: fmtNum(secDist?.total_shares_issued),
      web: null,
      status: 'unavailable',
    },
    {
      label: 'SEC Filing Type',
      gpp: null,
      sec: props.secFiling?.filing_type ?? null,
      secSub: props.secFiling?.filing_date ?? null,
      web: null,
      status: 'unavailable',
    },
    {
      label: 'GPP Data Source',
      gpp: (() => {
        const ds = props.gppData?.data_source
        if (ds == null) return null
        if (typeof ds === 'object') return Object.values(ds as Record<string, string>).join(', ')
        return String(ds)
      })(),
      gppSub: `status: ${props.gppData?.status ?? '—'}`,
      sec: null,
      web: null,
      status: 'unavailable',
    },
    {
      label: 'GPP Performance IDs',
      gpp: (() => {
        const ids = props.gppData?.performance_ids_by_class ?? {}
        const entries = Object.entries(ids).map(([k, v]) => `${k}: ${v}`)
        return entries.length ? entries.join(' · ') : null
      })(),
      sec: null,
      web: null,
      status: 'unavailable',
    },
    {
      label: 'Website URL',
      gpp: null,
      sec: null,
      web: props.websiteUrl ?? null,
      status: 'unavailable',
    },
  ]
})
</script>
