<!-- Generated by Copilot -->
<!-- NavTab: NAV comparison across SEC, Website, GPP per share class -->
<template>
  <div>
    <div class="mb-4 grid grid-cols-2 gap-4 text-sm">
      <div class="bg-gray-50 rounded-lg p-3">
        <span class="text-gray-500">SEC NAV Date:</span>
        <span class="ml-2 font-medium">{{ comparison.nav_date_sec ?? '—' }}</span>
      </div>
      <div class="bg-gray-50 rounded-lg p-3">
        <span class="text-gray-500">Website NAV Date:</span>
        <span class="ml-2 font-medium">{{ comparison.nav_date_website ?? '—' }}</span>
      </div>
    </div>

    <div class="overflow-x-auto rounded-lg border border-gray-200">
      <table class="min-w-full divide-y divide-gray-200 text-sm">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Share Class</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">SEC NAV</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Website NAV</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">GPP NAV</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Difference</th>
            <th class="px-4 py-3 text-center font-semibold text-gray-600">Status</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-100 bg-white">
          <tr v-for="(cls, name) in comparison.per_class" :key="name" class="hover:bg-gray-50">
            <td class="px-4 py-3 font-medium text-gray-900">{{ name }}</td>
            <td class="px-4 py-3 text-right">{{ fmt(cls.sec_nav) }}</td>
            <td class="px-4 py-3 text-right">{{ fmt(cls.website_nav) }}</td>
            <td class="px-4 py-3 text-right">{{ gppNav(name) }}</td>
            <td class="px-4 py-3 text-right" :class="cls.difference !== null && cls.difference !== 0 ? 'text-yellow-700 font-semibold' : ''">
              {{ cls.difference !== null ? (cls.difference > 0 ? '+' : '') + cls.difference.toFixed(4) : '—' }}
            </td>
            <td class="px-4 py-3 text-center">
              <StatusBadge :status="cls.status" />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ComparisonDetail } from '~/types/comparison'

const props = defineProps<{
  comparison: ComparisonDetail['comparison']
  performance: ComparisonDetail['performance']
}>()

function fmt(v: number | null | undefined) {
  return v != null ? `$${v.toFixed(4)}` : '—'
}

function gppNav(className: string) {
  const cls = props.performance?.per_class?.[className]
  return cls?.nav_per_share != null ? `$${cls.nav_per_share.toFixed(4)}` : '—'
}
</script>
