<!-- Generated by Copilot -->
<!-- SharesTab: total shares issued + per-class breakdown with % of total -->
<template>
  <div class="space-y-6">
    <!-- Total -->
    <div class="bg-indigo-50 rounded-lg p-4 flex items-center justify-between">
      <span class="text-sm text-indigo-700 font-medium">Total Shares Issued</span>
      <span class="text-lg font-bold text-indigo-900">{{ fmtNum(shares.total_shares_issued) }}</span>
    </div>

    <!-- Per-class -->
    <div class="overflow-x-auto rounded-lg border border-gray-200">
      <table class="min-w-full divide-y divide-gray-200 text-sm">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Share Class</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">Shares Issued</th>
            <th class="px-4 py-3 text-right font-semibold text-gray-600">% of Total</th>
            <!-- Simple visual bar -->
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Allocation</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-100 bg-white">
          <tr v-for="(cls, name) in shares.per_class" :key="name" class="hover:bg-gray-50">
            <td class="px-4 py-3 font-medium text-gray-900">{{ name }}</td>
            <td class="px-4 py-3 text-right">{{ fmtNum(cls.shares_issued) }}</td>
            <td class="px-4 py-3 text-right">{{ cls.percent_of_total != null ? cls.percent_of_total.toFixed(2) + '%' : '—' }}</td>
            <td class="px-4 py-3">
              <div class="h-2.5 rounded-full bg-gray-100 w-48">
                <div
                  class="h-2.5 rounded-full bg-indigo-500"
                  :style="{ width: (cls.percent_of_total ?? 0) + '%' }"
                />
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ComparisonDetail } from '~/types/comparison'

defineProps<{
  shares: ComparisonDetail['shares_outstanding']
}>()

function fmtNum(v: number | null | undefined) {
  return v != null ? v.toLocaleString() : '—'
}
</script>
