<!-- Generated by Copilot -->
<!-- TnaTab: Total Net Assets comparison across GPP, SEC filing, and Website per share class -->
<template>
  <div class="space-y-6">

    <!-- Fund-level total NAV (SEC) -->
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
      <div class="bg-blue-50 rounded-lg p-4 text-center">
        <p class="text-xs text-blue-600 font-medium uppercase tracking-wide">Total NAV (SEC)</p>
        <p class="mt-1 text-lg font-bold text-blue-900">{{ fmtNum(secExt.total_nav) }}</p>
        <p class="text-xs text-blue-500 mt-0.5">{{ secExt.tna_date ?? '—' }}</p>
      </div>
      <div class="bg-purple-50 rounded-lg p-4 text-center">
        <p class="text-xs text-purple-600 font-medium uppercase tracking-wide">GPP Report Date</p>
        <p class="mt-1 text-lg font-bold text-purple-900">{{ gppData.report_date ?? '—' }}</p>
        <p class="text-xs text-purple-500 mt-0.5">{{ gppData.status ?? '—' }}</p>
      </div>
      <div class="bg-teal-50 rounded-lg p-4 text-center">
        <p class="text-xs text-teal-600 font-medium uppercase tracking-wide">Website Source</p>
        <p class="mt-1 text-sm font-semibold text-teal-900 truncate">
          <a
            v-if="websiteUrl"
            :href="websiteUrl"
            target="_blank"
            rel="noopener noreferrer"
            class="underline hover:text-teal-700 transition-colors"
          >{{ websiteUrl }}</a>
          <span v-else class="text-teal-400 italic">Not available</span>
        </p>
      </div>
    </div>

    <!-- Per-class TNA comparison table -->
    <div class="overflow-x-auto rounded-lg border border-gray-200">
      <table class="min-w-full divide-y divide-gray-200 text-sm">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-3 text-left font-semibold text-gray-600">Share Class</th>
            <th class="px-4 py-3 text-right font-semibold text-purple-700">
              <span class="flex items-center justify-end gap-1.5">
                <span class="w-2 h-2 rounded-full bg-purple-400 inline-block" />GPP TNA
              </span>
            </th>
            <th class="px-4 py-3 text-right font-semibold text-blue-700">
              <span class="flex items-center justify-end gap-1.5">
                <span class="w-2 h-2 rounded-full bg-blue-400 inline-block" />SEC TNA
              </span>
              <span class="block text-xs font-normal text-blue-400">{{ secExt.tna_date ?? '' }}</span>
            </th>
            <th class="px-4 py-3 text-right font-semibold text-teal-700">
              <span class="flex items-center justify-end gap-1.5">
                <span class="w-2 h-2 rounded-full bg-teal-400 inline-block" />Website TNA
              </span>
            </th>
            <th class="px-4 py-3 text-center font-semibold text-gray-600">Status</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-100 bg-white">
          <tr
            v-for="cls in allClasses"
            :key="cls"
            class="hover:bg-gray-50"
          >
            <td class="px-4 py-3 font-medium text-gray-900">{{ cls }}</td>
            <!-- GPP TNA (from ClassTNA section, latest entry for class) -->
            <td class="px-4 py-3 text-right font-mono">
              <span v-if="gppTna(cls) != null" class="text-purple-800">{{ fmtNum(gppTna(cls)) }}</span>
              <span v-else class="text-gray-400">—</span>
              <span v-if="gppTnaDate(cls)" class="block text-xs text-gray-400">{{ gppTnaDate(cls) }}</span>
            </td>
            <!-- SEC TNA -->
            <td class="px-4 py-3 text-right font-mono">
              <span v-if="secTna(cls) != null" class="text-blue-800">{{ fmtNum(secTna(cls)) }}</span>
              <span v-else class="text-gray-400">—</span>
            </td>
            <!-- Website TNA -->
            <td class="px-4 py-3 text-right font-mono">
              <span v-if="webTna(cls) != null" class="text-teal-800">{{ fmtNum(webTna(cls)) }}</span>
              <span v-else class="text-gray-400">—</span>
            </td>
            <!-- Status -->
            <td class="px-4 py-3 text-center">
              <StatusBadge :status="cmpTna(cls)" />
            </td>
          </tr>
          <!-- Empty state -->
          <tr v-if="allClasses.length === 0">
            <td colspan="5" class="px-4 py-8 text-center text-sm text-gray-400 italic">
              No TNA data available
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Website source footer -->
    <p v-if="websiteUrl" class="text-xs text-gray-400">
      Website TNA sourced from
      <a :href="websiteUrl" target="_blank" rel="noopener noreferrer" class="underline hover:text-gray-600 transition-colors">{{ websiteUrl }}</a>
    </p>

  </div>
</template>

<script setup lang="ts">
// Generated by Copilot
import type { ComparisonDetail, GppSectionEntry } from '~/types/comparison'

const props = defineProps<{
  secFiling: ComparisonDetail['sec_filing']
  gppData: ComparisonDetail['gpp_data']
  performance: ComparisonDetail['performance']
  websiteUrl: string | null
}>()

const secExt = computed(() => props.secFiling?.extraction ?? {
  total_nav: null,
  tna_date: null,
  tna_per_class: {},
  nav_date: null,
  nav_per_share: {},
  distribution_data: { declaration_date: null, record_date: null, payment_date: null, per_class: {}, total_shares_issued: null, shares_per_class: {} },
})

// All share classes — union from SEC, GPP ClassTNA section, and website performance
const allClasses = computed(() => {
  const set = new Set<string>()
  Object.keys(secExt.value.tna_per_class ?? {}).forEach(k => set.add(k))
  Object.keys(props.performance?.per_class ?? {}).forEach(k => set.add(k))
  const clsTnaSection = props.gppData?.sections?.['ClassTNA'] ?? []
  for (const entry of clsTnaSection) {
    for (const k of Object.keys(entry)) {
      if (k !== 'PerformanceId' && k !== 'Date') set.add(k)
    }
  }
  return Array.from(set).sort()
})

// GPP ClassTNA — latest entry for the given class
function gppTnaEntry(cls: string): GppSectionEntry | null {
  const pts = props.gppData?.sections?.['ClassTNA'] ?? []
  const relevant = pts.filter(p => p[cls] != null)
  return relevant.length ? relevant[relevant.length - 1] : null
}
function gppTna(cls: string): number | null {
  const e = gppTnaEntry(cls)
  return e ? (e[cls] as number ?? null) : null
}
function gppTnaDate(cls: string): string | null {
  return gppTnaEntry(cls)?.Date ?? null
}

function secTna(cls: string): number | null {
  return (secExt.value.tna_per_class as Record<string, number | null>)?.[cls] ?? null
}

function webTna(cls: string): number | null {
  return props.performance?.per_class?.[cls]?.tna ?? null
}

/** Numeric comparison with tolerance */
function cmpTna(cls: string): 'match' | 'mismatch' | 'unavailable' {
  const vals = [gppTna(cls), secTna(cls), webTna(cls)].filter(v => v != null) as number[]
  if (vals.length < 2) return 'unavailable'
  const min = Math.min(...vals)
  const max = Math.max(...vals)
  return (max - min) < 0.001 ? 'match' : 'mismatch'
}

function fmtNum(v: number | null | undefined) {
  return v != null ? v.toLocaleString(undefined, { maximumFractionDigits: 2 }) : '—'
}
</script>
