// Generated by Copilot
// Data adapter — supports 'local' (fs) and 's3' (AWS S3) data sources.
// Switch with the DATA_SOURCE environment variable (default: 'local').
// S3 uses the IAM instance role on App Runner; no key/secret env vars required.

import { readFile, readdir } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import {
  S3Client,
  GetObjectCommand,
  ListObjectsV2Command,
} from '@aws-sdk/client-s3'
import type { CIKListEntry, ComparisonDetail } from '../types/comparison'

// ─── Local helpers ──────────────────────────────────────────────────────────

const DATA_DIR = resolve(process.cwd(), 'data')

async function localListDates(): Promise<string[]> {
  const entries = await readdir(DATA_DIR, { withFileTypes: true })
  return entries
    .filter(e => e.isDirectory() && /^\d{4}-\d{2}-\d{2}$/.test(e.name))
    .map(e => e.name)
    .sort()
    .reverse()
}

async function localListComparisons(date: string): Promise<CIKListEntry[]> {
  const raw = await readFile(join(DATA_DIR, date, 'index.json'), 'utf8')
  return JSON.parse(raw) as CIKListEntry[]
}

async function localGetComparison(date: string, cik: string): Promise<ComparisonDetail> {
  const raw = await readFile(join(DATA_DIR, date, `${cik}.json`), 'utf8')
  return JSON.parse(raw) as ComparisonDetail
}

// ─── S3 helpers ─────────────────────────────────────────────────────────────

function buildS3Client(region: string) {
  return new S3Client({ region })
}

/** Stream a S3 GetObject body to a string (AWS SDK v3 SdkStreamMixin provides transformToString) */
async function s3ObjectToString(body: { transformToString(): Promise<string> } | undefined): Promise<string> {
  if (!body) throw new Error('S3 response body is empty')
  return body.transformToString()
}

async function s3ListDates(client: S3Client, bucket: string, prefix: string): Promise<string[]> {
  // List common prefixes one level deep → each represents a date folder
  const response = await client.send(
    new ListObjectsV2Command({
      Bucket: bucket,
      Prefix: prefix,
      Delimiter: '/',
    }),
  )
  const dates: string[] = []
  for (const cp of response.CommonPrefixes ?? []) {
    // cp.Prefix looks like "data/2026-02-20/" — strip the leading prefix and trailing slash
    const segment = (cp.Prefix ?? '').slice(prefix.length).replace(/\/$/, '')
    if (/^\d{4}-\d{2}-\d{2}$/.test(segment)) {
      dates.push(segment)
    }
  }
  return dates.sort().reverse()
}

async function s3ListComparisons(
  client: S3Client,
  bucket: string,
  prefix: string,
  date: string,
): Promise<CIKListEntry[]> {
  const key = `${prefix}${date}/index.json`
  const response = await client.send(new GetObjectCommand({ Bucket: bucket, Key: key }))
  const raw = await s3ObjectToString(response.Body)
  return JSON.parse(raw) as CIKListEntry[]
}

async function s3GetComparison(
  client: S3Client,
  bucket: string,
  prefix: string,
  date: string,
  cik: string,
): Promise<ComparisonDetail> {
  const key = `${prefix}${date}/${cik}.json`
  const response = await client.send(new GetObjectCommand({ Bucket: bucket, Key: key }))
  const raw = await s3ObjectToString(response.Body)
  return JSON.parse(raw) as ComparisonDetail
}

// ─── Public API (called by Nitro server routes) ──────────────────────────────

/** Return sorted list of available date folders (yyyy-mm-dd) */
export async function listDates(): Promise<string[]> {
  const config = useRuntimeConfig()
  if (config.dataSource === 's3') {
    const client = buildS3Client(config.s3Region)
    return s3ListDates(client, config.s3Bucket, config.s3Prefix)
  }
  return localListDates()
}

/** Return the CIK summary list for a given date */
export async function listComparisons(date: string): Promise<CIKListEntry[]> {
  const config = useRuntimeConfig()
  if (config.dataSource === 's3') {
    const client = buildS3Client(config.s3Region)
    return s3ListComparisons(client, config.s3Bucket, config.s3Prefix, date)
  }
  return localListComparisons(date)
}

/** Return the full comparison detail for a given date + CIK */
export async function getComparison(date: string, cik: string): Promise<ComparisonDetail> {
  const config = useRuntimeConfig()
  if (config.dataSource === 's3') {
    const client = buildS3Client(config.s3Region)
    return s3GetComparison(client, config.s3Bucket, config.s3Prefix, date, cik)
  }
  return localGetComparison(date, cik)
}

