// Generated by Copilot
// GET /api/comparison/:date/:cik — returns full comparison detail
// getComparison is auto-imported from server/utils/dataAdapter
export default defineEventHandler(async (event) => {
  const date = getRouterParam(event, 'date')!
  const cik = getRouterParam(event, 'cik')!
  return await getComparison(date, cik)
})
