// Generated by Copilot
// Shared TypeScript types for comparison data

export interface CIKListEntry {
  cik: string
  fund_name: string
  overall_status: 'match' | 'mismatch' | 'error' | 'ok'
  timestamp: string
}

export interface ClassNavComparison {
  sec_nav: number | null
  website_nav: number | null
  difference: number | null
  status: string
}

export interface ClassDistribution {
  gross_distribution: number | null
  servicing_fee: number | null
  net_distribution: number | null
}

export interface ClassShares {
  shares_issued: number | null
  percent_of_total: number | null
}

/** One row in a GPP section (per-class format: { PerformanceId, Date, "Class X": value }) */
export interface GppSectionEntry {
  PerformanceId: string
  Date: string
  [shareClass: string]: string | number | null
}

/** @deprecated Use GppSectionEntry */
export interface GppSection {
  date: string
  value: number | null
}

export interface GppNavComparison {
  sec_nav: number | null
  website_nav: number | null
  gpp_price: number | null
  gpp_price_date: string | null
  sec_vs_gpp_diff: number | null
  website_vs_gpp_diff: number | null
}

export interface GppComparison {
  gpp_latest: {
    Price: number | null
    Dividend: number | null
    ClassTNA: number | null
  }
  nav_per_class: Record<string, GppNavComparison>
}

export interface ComparisonDetail {
  fund: {
    name: string
    cik: string
    generated_at: string
  }
  sec_filing: {
    filing_type: string | null
    filing_date: string | null
    filing_url: string | null
    accession_number: string | null
    extraction: {
      nav_date: string | null
      nav_per_share: Record<string, number | null>
      total_nav: number | null
      tna_per_class: Record<string, number | null>
      tna_date: string | null
      distribution_data: {
        declaration_date: string | null
        record_date: string | null
        payment_date: string | null
        per_class: Record<string, ClassDistribution>
        total_shares_issued: number | null
        shares_per_class: Record<string, number | null>
      }
    }
  }
  website: {
    url: string | null
    share_classes: Record<string, {
      share_class: string
      extraction_timestamp: string | null
      annualized_distribution_rate: number | null
      nav_per_share: number | null
      nav_date: string | null
      historical_nav: Array<{ date: string; nav: number }>
    }>
  }
  comparison: {
    nav_date_sec: string | null
    nav_date_website: string | null
    per_class: Record<string, ClassNavComparison>
  }
  distributions: {
    declaration_date: string | null
    record_date: string | null
    payment_date: string | null
    per_class: Record<string, ClassDistribution>
  }
  shares_outstanding: {
    total_shares_issued: number | null
    per_class: Record<string, ClassShares>
  }
  performance: {
    per_class: Record<string, {
      nav_per_share: number | null
      annualized_distribution_rate: number | null
      nav_date: string | null
      tna: number | null
    }>
  }
  historical_nav: unknown | null
  gpp_data: {
    fund_name: string
    cik: string
    report_date: string | null
    accession_number?: string | null
    performance_ids_by_class: Record<string, string>
    data_source: string | { combined_data: string; extracted_data: string } | null
    status: string
    reason: string | null
    by_class: Record<string, unknown>
    sections: Record<string, GppSectionEntry[]>
    /** @deprecated */
    performance_id?: string | null
    /** @deprecated */
    expected_sections?: string[]
  }
  gpp_comparison?: GppComparison
}
